blank_issues_enabled: false
contact_links:
  - name: farm-ng Community Support
    url: https://discourse.farm-ng.com/
    about: Please ask and answer questions here.
    - name: Open a feature request
    url: https://github.com/farm-ng/farm-ng-amiga/issues/new/choose
    about: Please open feature requests in the `farm-ng-amiga` repository.
  - name: Open a bug report
    url: https://github.com/farm-ng/farm-ng-amiga/issues/new/choose
    about: Please open bug reports in the `farm-ng-amiga` repository.
