/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  "docs": {
    "Introduction": [
      "getting-started",
      "index",
    ],
    "Getting Started": [
      "amiga_quick_start/amiga-quick-start",
      "dashboard/dashboard-fw",
      "brain/brain-install",
      "brain/next-steps",
    ],
    "Amiga Overview": [
      "dashboard/dashboard",
      "dashboard/control-states",
      "debug_cable/debug-cable",
      "debug_cable/service-cable",
      "mcu_kit/microcontroller-kit",
      "brain/brain",
      "pendant/pendant",
    ],
    "Resources/Support": [
      "hardware-tools/recommended-tools",
      "reference/faq",
      "support/support",
    ],
  },
  "api": [
    "api",
    {
      "CircuitPython ADK": [
        require("./docs/reference/circuitpy/sidebar.json")
      ],
    },
    {
      "Brain ADK": [
        require("./docs/reference/brain/sidebar.json")
      ],
    }
  ],
  "examples": {
    "Index": ["examples/examples-index"],
    "CircuitPython Example" : [
        "examples/hello_main_loop/hello-world",
        "examples/cansniffer/cansniffer",
        "examples/FPV/fpv",
    ],
    "Brain Example" : [
        "examples/import_log_file/import-log-file",
        "examples/file_reader/file-reader",
        "examples/file_reader_can/file-reader-can",
        "examples/camera_client/camera-client",
        "examples/camera_client_gui/camera-client-gui",
    ],
    "Virtual Joystick Tutorial" :[
        "examples/virtual_joystick/virtual-joystick-overview",
        "examples/virtual_joystick/template-starter",
        "examples/virtual_joystick/template-overview",
        "examples/virtual_joystick/canbus-stream",
        "examples/virtual_joystick/camera-stream",
        "examples/virtual_joystick/virtual-joystick-widget",
        "examples/virtual_joystick/auto-control",
        "examples/virtual_joystick/further-exercises",
    ],
    "Developing Custom Applications": [
      "brain/brain-apps"
    ]
},
  "contribute": [
    "contribute/contribute-website"
  ]
};

module.exports = sidebars;
